### ISSUE TITLE
Rename repository to vc-core-storefront

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#1]
Currently we have the following repos:
vc-storefront
vc-theme-*
vc-platform
vc-module-*

After migration to .NET Core we may want to have the following structure:
vc-core-storefront
vc-core-platform
vc-core-module-*

instead of
vc-storefront-core
vc-platform-core
vc-module-*-core

**Comment by Woland2k** [comment]
i agree

**Comment by asvishnyakov** [comment]
Also, it's safe to rename any repo, because GitHub will redirect all your request to old repo url to new url, including git commands like fetch & pull

**Comment by tatarincev** [comment]
We already have an agreement about repository naming.
