### ISSUE TITLE
Add search on derivatives

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#101]
Add search & get methods to derivative service & API controller for them.

On converting storefront search criteria to module search criteria, pass current customer Id as single item of MemberIds, fulfillment center Ids (https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront.Model/Stores/Store.cs#L108) as items 
of FulfillmentCenterIds.

Updated:
![38129633-43a20e16-3419-11e8-859b-e6cab291a21a](https://user-images.githubusercontent.com/6369252/38129694-7e1d2a6c-3419-11e8-969a-ce37a23e71aa.png)

Old:
![image](https://user-images.githubusercontent.com/6369252/38075736-dafa45a8-334c-11e8-81d1-ac091cfdb516.png)

**Comment by Woland2k** [comment]
@asvishnyakov why is this needed in the store core? What is the derivative?

**Comment by asvishnyakov** [comment]
@Woland2k [Derivative](https://en.wikipedia.org/wiki/Derivative_(finance)) is a business term, it's special finance instrument, contract for which client and/or seller get a right or take a commitment to buy or sell product. We need it in our client project, where one of product categories may have Forward Contract (it's one of type of derivatives): with this contract, client *must* buy and seller *must* sell product in specified date range with special (usually lower) price. Because it's probably useful B2B feature, we gave it to public space: we made vc-module-derivatives and this changes in storefront and in client project we will only customize models & write custom UI in our storefront theme.

**Comment by asvishnyakov** [comment]
@Woland2k Contract is too general term. In business it has concrete terms: Derivatives for all of these contracts, Futures, Options, Forwards (and also Swaps, REPOs which used in stock exchange only) for special types. So I prefer use it, it will prevent misunderstanding.

**Comment by Woland2k** [comment]
@asvishnyakov derivatives is a math term, so when you say Derivatives module without context, it has no meaning. You can name module vc-module-derivative-contract, but I would rather just have contracts.

**Comment by asvishnyakov** [comment]
@eMazeika I missed sorting support on search; add SortBy property to SearchCriteria, please, and it to Sort property of dto on convertation. Like this: https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs#L240

**Comment by Woland2k** [comment]
@asvishnyakov still, it is very unclear what it is for, word contract should be in the name of the module

**Comment by eMazeika** [comment]
guys, there are lots of places to clarify and set the context. Some of them:
- readme
- module manifest (name, description)
- description in github repository

**Comment by Woland2k** [comment]
@emazeika name of the module should be obvious

**Comment by eMazeika** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/pull/103/commits/08e8933d82a3df0dda666af866f97bc7585bf2ee
