### ISSUE TITLE
Subscription interval shown as number on the subscription details page

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-storefront-core#109]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: any
- Platform version: any
- Storefront version: 3.1.3

### Expected behavior

Subscription interval should be displayed in text on the subscription details page
### Actual behavior
it shows number instead of interval name:
![subscription_issue](https://user-images.githubusercontent.com/5917756/40083011-787fa158-5858-11e8-8f9f-3332f64b81e7.jpg)

**Comment by benb1n** [comment]
There is a similar issue on the subscription list page that prevents the "Period" column from displaying.  There is a JS error in the console:

```
TypeError: data.interval.toLowerCase is not a function
    at account-subscriptions.js:77
    at Array.fn1 (eval at compile (angular.js:14605), <anonymous>:4:962)
    at expressionInputsWatch (angular.js:15754)
    at Scope.$digest (angular.js:17277)
    at Scope.$apply (angular.js:17552)
    at done (angular.js:11697)
    at completeRequest (angular.js:11903)
    at XMLHttpRequest.requestLoaded (angular.js:11836)
```

@IgorisB

**Comment by Andrew-Orlov** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/pull/185

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/v3.2.7
