### ISSUE TITLE
User role is cached

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#112]
Version info: 
- Browser version: Chrome 66
- Platform version: 2.13.27
- Storefront version: 3.1.4

### Expected behavior
Role should be changed immediately

### Actual behavior
Role changed only after storefront restarting

### Steps to reproduce
1. Set any role to user
2. Go to My account in storefront
3. See current role
4. Change the role
5. Go to My account in storefront
6. ???

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.1
