### ISSUE TITLE
OrderEventsHandler creates duplicate Addresses for same address

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#116]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome 66.0.3359.181
- Platform version: 2.13.26
- Storefront version: 3.1.3

### Expected behavior
Only create new addresses for customer if the address given during checkout is different

### Actual behavior
Creates a new entry for the exact same address

### Steps to reproduce
1.  Walk through checkout for a customer with an existing address.
2.  Choose that address for the shipping addresss
3.  Complete checkout.
4.  Verify that the customer has a new address.

@IgorisB

**Comment by tatarincev** [comment]
To completely fix this issue need to update follow modules to latest version and use storefront from dev branch until we do not make the new release
[vc-module-cart](https://github.com/VirtoCommerce/vc-module-cart/releases)
[vc-module-order](https://github.com/VirtoCommerce/vc-module-order/releases)

**Comment by tatarincev** [comment]
On this week immediately after migration to the .NET Core 2.1

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.0
