### ISSUE TITLE
Angular error on account.addresses view

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#117]
Version info: 
Browser version: Chrome 66.0.3359.181
Platform version: 2.13.26
Storefront version: 3.1.3

![image](https://user-images.githubusercontent.com/1915482/41057704-71c93bbc-698d-11e8-927a-04d11fac98b4.png)

### Expected behavior
No JS errors in console.  Note that page appears to work fine.

### Actual behavior
See above screenshot - Angular throws multiple exceptions.

### Steps to reproduce
1.  Open Chrome dev tools
2.  View account addresses page.

**Comment by yecli** [comment]
Platform version: 2.13.38
Storefront: 3,2,6
Theme: Default Electronics theme

Unable to reproduce locally and on https://demo.virtocommerce.com/.
Maybe it was already fixed or the are some specific conditions to repeat this problem.
