### ISSUE TITLE
LiquidCart is not available to Liquid view engine

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#118]
https://github.com/VirtoCommerce/vc-storefront-core/blob/3e5fe4d4985b7ef2cce5b33c792921f8e4eddf64/VirtoCommerce.LiquidThemeEngine/Converters/ShopifyContextConverter.cs#L51

We're trying to access the Shopify cart object in a liquid template, but cart is null.  See link above.  The cart isn't created yet in our use case, so this line ignores converting it for Shopify to use.  I was able to fix it by changing it to access and create the value

```
result.Cart = workContext.CurrentCart != null && workContext.CurrentCart.Value != null ? ToLiquidCart(workContext.CurrentCart.Value, workContext.CurrentLanguage, urlBuilder) : null;
```

I don't know if there are any drawbacks to this, performance or otherwise.

We're on storefront version 3.1.4 and platform 2.13.26.

@IgorisB

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
