### ISSUE TITLE
[ValidateAntiForgeryToken] broke invoice PDF

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#123]
https://github.com/VirtoCommerce/vc-storefront-core/blob/22b4d9207f4051ad43e5c80d14718aa95f7f878f/VirtoCommerce.Storefront/Controllers/Api/ApiOrderController.cs#L159

Adding `[ValidateAntiForgeryToken]` to the controller in a recent commit broke the invoice PDF endpoint.  It works if I remove that attribute.

@IgorisB

**Comment by Woland2k** [comment]
@tatarincev do we have an automated test for this?

**Comment by tatarincev** [comment]
Fixed and released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.1
