### ISSUE TITLE
Add customer login name into Application Insight events

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#141]
As a support team, I want to get customer name if an error occurs

Now even though information about exception contained a lot of useful info, we cannot relate it to a specific authenticated user.

Business Goal:
Know about any issue before your user.
How many users are affected?

https://hajekj.net/2017/03/13/tracking-currently-signed-in-user-in-application-insights/

**Comment by asvishnyakov** [comment]
@tatarincev Be careful about GDPR

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.4
