### ISSUE TITLE
Subscription cache does not invalidate when prototype order changes in platform

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#142]
Version info: 
- Browser version:  Chrome 68.0.3440.75
- Platform version: 2.13.30
- Storefront version: 3.2.1

### Expected behavior
When something on a subscriptions order prototype is changed in the platform, the storefront cache for that subscription should invalidate.  Examples:  line item is added/updated/deleted, order discount amount changed, etc.

### Actual behavior
The storefront continues to show the old version of the data.  The ModifiedDate on the prototype's order operation changes, but the subscription does not.  The current polling mechanism only looks for changes on the subscription's modified date.  Either this pooling needs to change or changes in platform to the prototype should also update the subscription's modified date.

### Steps to reproduce
1. Open an existing subscription in storefront. 
2. Open the same subscription in platform.
2.  Add a new item to the subscription and save.
3.  Refresh the subscription in storefront and note that the old subscription data is still showing.

@IgorisB

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.7

**Comment by benb1n** [comment]
Thanks @tatarincev for the quick turnaround!  This fixed the issue.
