### ISSUE TITLE
Request for product variations too long error

### ISSUE THREAD

**Issue by pungiish** [VirtoCommerce/vc-storefront-core#148]
Please provide detailed information about your issue, thank you!

I am getting a 500 internal server error when accessing a product with a lot of variations(20+) because the request url is too long.

requested url: http://localhost:80/admin/api/subscriptions/plans?ids=fb3a7301e4d14bd6aa6fa40a670f52c6&amp;ids=014b4f6a94064dd9971e450616da475e&amp;ids=0608f016686a4589ab67e8a153f891c2&amp;ids=06766e1fcfc747b99cf5e7b94b716471&amp;ids=0a5e8555568140c7908d9f12b8a65fe5&amp;ids=0b1804a04f2f4827bb4e6099fd914ab8&amp;ids=0b759e7264874dc38e511783077e9848&amp;ids=10b3e1b52f0a404eac1a41f7a961cf3e&amp;ids=15a025d808ee4cfda4c707ba2b055550&amp;ids=17bd72776df040b0b87c60290ce74d96&amp;ids=183f9c103e4b4c978258f46ad3d129dc&amp;ids=1a215e1eeb474d36bb3f82018ef8746a&amp;ids=1d06622f4ba34b1c9da43e80c8dff3bc&amp;ids=2199b3de93104446b7ee546ae0cef7b3&amp;ids=2440830c1cb342ad90af2adf9f29e1e5&amp;ids=257c6e8754644f489b0c56dad0080e78&amp;ids=25d5559783524e4ebe4c4c3c42d921dc&amp;ids=267e9ae3e5754c69a69ddfc92ee5d073&amp;ids=2f2b866697904d6eaea7777ccd3cb667&amp;ids=448d53df2969485499d7b8aae238573e&amp;ids=4883358b8a12483c8ddb646b9800dea7&amp;ids=49f00877a2f74c7188f63db5d4f4287e&amp;ids=4aeb26c6e595462cb93523bafc4cceff&amp;ids=4d8e8f4f7ba946028928e6d16245e3a9&amp;ids=50f431fb19604e15b3d7cfc8b203c09c&amp;ids=52f5cfcb610d447ba8582a4e221ab734&amp;ids=57fdeaa93be2492496efeebceb97e810&amp;ids=5d4aeaddcac9433caa23a09530fca208&amp;ids=5ee218a0b70642c3925bef5df0666a1e&amp;ids=5f37dc0b8fc14f71827b10c3c6341ab7&amp;ids=626a5c5ec2b947b8ae48fb9d5729d501&amp;ids=674e5b297cdc4926a1a4b0ac58470196&amp;ids=6efea8cc86734df2a78f2bb34757ee3e&amp;ids=71c304144094470db628674006cf7aab&amp;ids=72e2f78099b1481e8db99f3c37da9690&amp;ids=739178e993b04d71ae9bf5b799c8b155&amp;ids=775f5a72a8b349dab636ce1b03c92778&amp;ids=8b5f473c8792409b8734ab356010d02e&amp;ids=8e75e8de4ba0499fb0d15de079217eff&amp;ids=90ae5313b1dd4ad5bced3f602bbd33bb&amp;ids=9487869569e04e198561f44c282dc897&amp;ids=9eb97e967f60491ea4c3763be07e3323&amp;ids=a1ae2753587f4d8784fc7d4b3c1c81a6&amp;ids=a3484c7a27fd44a89d9e514f76994fce&amp;ids=a4b5e8ad7d1a4f0886ec2697a1c766db&amp;ids=ab7b431844f8425c9caaa09e78b08382&amp;ids=af69b75b3c9c4ee59a3dcf102ff4eab7&amp;ids=b08ceaa194f0482080d5f90705fa81bc&amp;ids=b2d85be8b39744c29de5c4e360672bbf&amp;ids=b3b51e6c81dc45c0b9aa5a1e8650e0e4&amp;ids=bc43da88f94842d29c64db913d163d6b&amp;ids=bd4d6186aa1a426a8f9e11c5bb537696&amp;ids=c0b570cf616a4332afe2f1ad51f624bf&amp;ids=c1a4c8848a3e443e82521d7585a7889e&amp;ids=c39948a019e74dfaa6bfaa4feb6566f6&amp;ids=c51d5d3658dc450493592ec2cd5e3e52&amp;ids=c5f00e2e23764080ad8b256f55079f6d&amp;ids=c9ff291fe97744fe84c4d41add5a653b&amp;ids=cac425bd59d140bb9ebf07e63d2b04f0&amp;ids=cfb9f3ac72274c7dbc84b0bbd3ac1af5&amp;ids=d23cbd32b363493684d69c752f910a6c&amp;ids=d4efcea6274343a8bd553c595b7c363b&amp;ids=d8541e1e8f7e4a57b8cba5030a25dc8e&amp;ids=d9008f736eba4763a6904a0a6ad670ac&amp;ids=dd00818221214e998f5573ad82d11135&amp;ids=f6fc5002a1be46169ee09954c1e1ff6d%3C/td%3E%3C/tr%3E%20%3Ctr%3E%3Cth%3EPhysical%20Path%3C/th%3E%3Ctd%3E&nbsp;&nbsp;&nbsp;C:\vc-platform\VirtoCommerce.Platform.Web\api\subscriptions\plans

Request filtering is configured on the Web server to deny the request because the query string is too long.

Version info: 
- Browser version: 
- Platform version: 
- Storefront version: .net core

### Expected behavior
Displaying the product and it's variations correctly.
### Actual behavior
Can't see the products variations, can't add the product to cart, error.
### Steps to reproduce
1. Configure VC platform and storefront core,
2. Import products with 20+ variations,
3. Go to the storefront and select the product.

**Comment by tatarincev** [comment]
@pungiish  Ok, seems to we need to add new API method in the subscription module POST api/subscriptions/plans/plenty to pass the product identifiers in the request body instead of query string

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-subscription/releases/tag/v1.1.8

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
