### ISSUE TITLE
Forgot Username returns a 404 page

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-storefront-core#150]
Version info: 
- Browser version: latest Chrome
- Platform version: 2.13.35
- Storefront version:  demo site

### Expected behavior
When I click the forgot username link, I can recover my username.

### Actual behavior
I get a 404 error.  https://demo.virtocommerce.com/Electronics/en-US/account/forgotlogin

### Steps to reproduce
1.  Go to the demo storefront.
2.  Click "Sign in" link.
3.  Click "Forgot your username" link.
4.  Note 404 error.

@IgorisB

**Comment by tatarincev** [comment]
@benb1n Thanks for your bug report, seems we add this action only in the theme :)

**Comment by tatarincev** [comment]
@benb1n  Fixed in dev

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
