### ISSUE TITLE
Implement AntiForgery token generation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#16]
- Need to create new Liquid tag for AntiForgery  token generation `{{ anti_forgery }}`

- Remove unconditional AntiForgery  token generation from Form tag
https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.LiquidThemeEngine/Tags/FormTag.cs#L83

**Comment by Woland2k** [comment]
@tatarincev what is the reason to creating another tag instead of reusing forms? Shouldn't all forms be verified?

**Comment by Woland2k** [comment]
There is no need for separate anti forgery tag. Each form should have one automatically.
