### ISSUE TITLE
Routing tests missed some routes

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#161]
After

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs#L55

Missed `POST storefrontapi/cart/payments`

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs#L312-L315

---

After

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs#L156

Missed `POST account/register` (form submit)

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront/Controllers/AccountController.cs#L82-L85

---

After

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs#L172

Missed `POST account/confirminvitation`

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront/Controllers/AccountController.cs#L173-L176

---

After

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront.Tests/Routing/RoutingTests.cs#L214

Missed `GET common/getcountries/json`, `GET common/getregions/{regionName}/json`

https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront/Controllers/CommonController.cs#L104-L106
https://github.com/VirtoCommerce/vc-storefront-core/blob/d3995f13ff65d72dbf5d90d3f1c648dc69009983/VirtoCommerce.Storefront/Controllers/CommonController.cs#L112-L114

**Comment by asvishnyakov** [comment]
@avas We added the following test
```
AddRegularRequestRoute(routingData, "Account", "Register", CustomHttpMethod.PostForm, "account/register")
```
on our fork, but it fails with:

> TestRouting(method: PostForm, url: "account/register", expectedControllerMethodName: "VirtoCommerce.Storefront.Controllers.AccountContro"..., objectToPost: null) [0:01.140] Failed: System.Net.Http.HttpRequestException : Error while copying content to a stream.
> System.Net.Http.HttpRequestException : Error while copying content to a stream.
> ---- System.IO.IOException : 
> -------- System.ArgumentNullException : Value cannot be null.
> Parameter name: o
>    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at VirtoCommerce.Storefront.Tests.Routing.RoutingTests.PerformSendingRequest(CustomHttpMethod method, String url, Object objectToPost) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront.Tests\Routing\RoutingTests.cs:line 349
>    at VirtoCommerce.Storefront.Tests.Routing.RoutingTests.PerformTestingRouting(CustomHttpMethod method, String url, String expectedControllerMethodName, Object objectToPost) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront.Tests\Routing\RoutingTests.cs:line 331
>    at VirtoCommerce.Storefront.Tests.Routing.RoutingTests.TestRouting(CustomHttpMethod method, String url, String expectedControllerMethodName, Object objectToPost) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront.Tests\Routing\RoutingTests.cs:line 317
> --- End of stack trace from previous location where exception was thrown ---
> ----- Inner Stack Trace -----
>    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
>    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
>    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
>    at Microsoft.AspNetCore.TestHost.ResponseStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
>    at System.Net.Http.StreamToStreamCopy.<>c.<DisposeSourceWhenCompleteAsync>b__1_0(Task completed, Object innerSource)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
> ----- Inner Stack Trace -----
>    at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JObject.FromObject(Object o, JsonSerializer jsonSerializer)
>    at VirtoCommerce.Storefront.JsonConverters.UserBackwardCompatibilityJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\JsonConverters\BackwardCompatibilityJsonConverter.cs:line 75
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
>    at Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at VirtoCommerce.Storefront.Startup.<>c.<<Configure>b__8_0>d.MoveNext() in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Startup.cs:line 374
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
>    at VirtoCommerce.Storefront.Middleware.ApiErrorHandlingMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\ApiErrorHandlingMiddleware.cs:line 25
>    at VirtoCommerce.Storefront.Middleware.ApiErrorHandlingMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\ApiErrorHandlingMiddleware.cs:line 55
>    at VirtoCommerce.Storefront.Middleware.CreateStorefrontRolesMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\CreateStorefrontRolesMiddleware.cs:line 53
>    at VirtoCommerce.Storefront.Middleware.NoLiquidThemeMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\NoLiquidThemeMiddleware.cs:line 33
>    at VirtoCommerce.Storefront.Middleware.StoreMaintenanceMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\StoreMaintenanceMiddleware.cs:line 26
>    at VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in E:\Programming\cmg-storefront-core\VirtoCommerce.Storefront\Middleware\WorkContextBuildMiddleware.cs:line 76
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()

Variant with `, new UserRegistration()` fails too.
All other tests run succesfully:
```
AddApiRequestRoute(routingData, "ApiCart", "AddOrUpdateCartPayment", CustomHttpMethod.PostJson, "storefrontapi/cart/payments");
AddRegularRequestRoute(routingData, "Account", "ConfirmInvitation", CustomHttpMethod.PostForm, "account/confirminvitation");
AddRegularRequestRoute(routingData, "Common", "GetCountries", CustomHttpMethod.Get, "common/getcountries/json");
AddRegularRequestRoute(routingData, "Common", "GetRegions", CustomHttpMethod.Get, "common/getregions/USA/json");
```

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
