### ISSUE TITLE
Object reference not set in MarketingConverter

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront-core#164]
Version info: 
- Storefront version:  latest dev

### Actual behavior
Exception
message: "Object reference not set to an instance of an object."

in line:
result.CustomerId = promoEvalContext.Cart.Customer.Id;

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
