### ISSUE TITLE
Nuget package updates

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#166]
Just wanted to ask, is there a specific reason why packages are lagging behind, there's currently 20 updates available from Nuget for the entire Storefront solution?

Among them all the ASP.NET Core updates some of which featured both new features and security fixes.

I'm having a problem because I try to keep my fork in sync with this upstream repo but I have a habit to always update packages in my repos at least when there are only minor version differences (to stay current with new packages issued, just a precaution of mine).

**Comment by tatarincev** [comment]
We have running https://dependabot.com/ on all our repositories which means that we will always be up to date :)
