### ISSUE TITLE
Internal server error in the latest platform release 

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#171]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: chrome
- Platform version: 2.13.36
- Storefront version: latest

### Expected behavior
Should not give exception

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/47478096-1d0dfb80-d7dd-11e8-8f2e-320627207644.png)

### Steps to reproduce
1. Install using docker: https://virtocommerce.com/docs/vc2devguide/deployment/deploy-using-docker
2. Open storefront

**Comment by tatarincev** [comment]
Fixed in this release https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.10
