### ISSUE TITLE
Bulk Order doesn't resolve Variation by SKU

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront-core#172]
### Expected behavior
As a customer, I can add variation from Bulk Add to Cart UI. 

### Actual behavior
As a customer, I can add the main product only

### Steps to reproduce
1. Copy Variation SKU
2. Open bulk order page https://demo.virtocommerce.com/bulkorder
3. Enter Variation code and  click Add to Cart
4. See error message: Products with following SKUs was not added to cart:

**Comment by tatarincev** [comment]
To fix this issue need to do follow steps:

-  Update `Catalog module` to this version (latest at the current moment) https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.11
- Re-index products in manager (Browse -> Search Index -> Select** Product** -> Build index -> Delete and build
- Get this fix from the storefront **dev** branch https://github.com/VirtoCommerce/vc-storefront-core/commit/fdac6772fd3c4fc53105532380df832d837ed993

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.6
