### ISSUE TITLE
Product sku missing on Product Liquid model

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#174]
Besides using variation SKUs we need to access the main product SKUs too in our Liquid views.

The Product catalog model does have a Sku property but the Liquid model which inherits from Drop does not.

I added it and also mapped it inside the ToLiquidProduct() function and it is now available on the client side. 

I was wondering why this isn't done so in the first place and if I'm doing something wrong.

**Comment by tatarincev** [comment]
@brgrz  Yes, the Liquid Product model is taken from **Shopify** product model that originally doesn't contains **Sku** property. May I ask  you create PR with these changes  to the storefront **dev** branch?

**Comment by brgrz** [comment]
I guess I could, hopefully asap.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/v3.2.7
