### ISSUE TITLE
RAM usage unusually high

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#175]
VS storefront is the first .NET Core app that we run on one of our production servers and immediately I started to notice the extremely high RAM usage. 

The ".NET Core Host" process would go up to 3 GB of ram usage regularly. Then we restart the site and it drops back to normal.

We are currently running with caching disabled because we're still working on a site and it gets multiple theme updates per day so we run without caching because we had issues with clearing the cache and seeing the changes but still, even with cache disabled (or precisely because of it) this high ram usage shouldn't be happening.

**Comment by tatarincev** [comment]
What is the load on your production server (online users, quantity of requests per time unit)? Try to play with decrease this setting value  `VirtoCommerce.CacheAbsoluteExpiration`

**Comment by brgrz** [comment]
The site gets 50-60 visits per day, so minimal. The process would go to 2,5-3 GB of RAM, then eventually everything (both platform and storefront) would stop working, producing 500 status code. Caching disabled.

**Comment by brgrz** [comment]
Intermediate report:

We updated the Nuget packages to the latest version (only the minor version updates), added AppInsights telemetry, set caching to true and absolute expiration to 3 hours and published the new build.

I am now seeing much better performance, specifically faster loading and the RAM usage more consistent (around 300 megs).
