### ISSUE TITLE
Storefront logging - not present?

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#176]
The only piece of code with regards to logging I found is this in Program.cs

              .ConfigureLogging((hostingContext, logging) =>
              {
                  logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                  logging.AddConsole();
                  logging.AddDebug();
              })

but I am unable to find any logs anywhere.

Also I couldn't find any documentation on configuring logging https://virtocommerce.com/docs/vc2devguide/working-with-storefront

Pretty much we have no clue/insight into what is going on with the storefront app.

**Comment by tatarincev** [comment]
The VC storefront is  ASP.NET Core application, and logging configuration  isn't  different  from default configuration for an other ASP.NET Core applications. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/
Debug configuration has the following  settings for logging and you might change it as you wish 
https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/appsettings.Development.json#L2

**Comment by brgrz** [comment]
Should a default logging be introduced into the codebase? Or did you have another method of logging/auditing in mind because I see you seem to rely on Azure Application Insights in certain places.

**Comment by tatarincev** [comment]
@brgrz We mainly use Application Insight for  logging, debugging, errors and performance monitoring  tasks on production env.

**Comment by brgrz** [comment]
Would it make sense to introduce a simple/basic logging solution for projects that don't use AI logs?

**Comment by tatarincev** [comment]
no one asks about it

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
