### ISSUE TITLE
Building client side JS app

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#178]
I had to make some changes to the code in /assets/js directory. 

I then installed npm packages using npm install and it brought down everything required by the package.json and then I ran gulp using the default gulpfile that comes with the codebase.

The process produced new bundles but now certain parts of the site don't work anymore.

For example, I can see the changes I made to the cart and cart works but user account administration does not work (some DI error related to angular).

Maybe it has to do with the large amount of JS errors (reported by lint when running gulp). There's a couple dozen of them.

**Comment by brgrz** [comment]
The DI issue I get after new gulp build is this 

https://code.angularjs.org/1.5.7/docs/error/$injector/unpr?p0=storefrontApp.mainContextProvider%20%3C-%20storefrontApp.mainContext

**Comment by tatarincev** [comment]
@brgrz  Could you provide public url to your storefront where I can see this error on my browser?

**Comment by brgrz** [comment]
I just figured out what was wrong. I downloaded again the latest vc-default-theme bits and recompiled JS with gulp, then copied it over to a working site and JS worked fine.

So I compared my current active code that is problematic and I discovered that I tried to fixed some issues reported by lint previously. Specifically this one

From this
```
var storefrontApp = angular.module('storefrontApp');
storefrontApp.controller('mainController', ['$scope', '$location', '$window', 'customerService', 'storefrontApp.mainContext',
```

to this
```
var context = angular.module('storefrontApp').mainContext;
storefrontApp.controller('mainController', ['$scope', '$location', '$window', 'customerService', 'context',
```

Apparently angular has issues with the corrected syntax.
