### ISSUE TITLE
Captcha, honeypot, bot protection?

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#179]
Any guidance with bot posting spam content protection? I am not seeing any captcha or honeypot integrated nor did I find any modules on the subject.

Should we do it ourselves?

**Comment by tatarincev** [comment]
Yes, storefront doesn't provide out of the box any of these tools. I suggest use our [vc-platform gitter chat channel](https://gitter.im/VirtoCommerce/vc-platform) chat for questions and communication, GitHub issues better use for features requests or bug reports.

**Comment by brgrz** [comment]
says on gitter you moved to discord, so which one then?
