### ISSUE TITLE
Replace DotLiquid with Scriban templating engine

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#188]
### The working branches
https://github.com/VirtoCommerce/vc-storefront-core/tree/features/scriban-migration
https://github.com/VirtoCommerce/vc-theme-default/tree/features/scriban-migration

### The comparison performance benchmark
200 concurrent users. 3 minutes test duration.  
![image](https://user-images.githubusercontent.com/7566324/50957867-f7cd8700-14c7-11e9-99d8-13e8eb12e0d0.png)

### The known theme breaking changes: 
- The specialized form tag has been removed `{% form 'login' %}{% endform %}` -> `<form accept-charset="UTF-8" action="{{ '~/account/login' | absolute_url }}" method="post" id="customer_login" name="customer_login"></form>`
- The pagination tag has been replaced to pipe function `{% paginate collection.products  by 5 %}{% endpaginate %}` -> `{{ paginator =  collection.products  | paginate 20 }}   {% if paginator.pages > 1 %}    {% include 'pagination-custom' %}`
- The special variable `blank` has a new behavior  `{{ variable != blank }}` before  equal to `variable  == null OR (IEnumerable)variable.Any()`. Must be replaced to `{{ variable.empty? == false }}` for collections.
https://github.com/lunet-io/scriban/issues/107
- Include statement doesn't support `{% include 'snippet' param1: aaa %}` -> `{% assign param1 = aaa %}{% include 'snippet' %}`
https://github.com/lunet-io/scriban/issues/106
- `current_tags contains tag` should be replaced to `current_tags[tag.value].empty? == false`
- named arguments don't support for functions are called as pipe and by direct call ` 'localization_key' | t: param1 : 'a', param2: 'b'` -> `'localization_key' | t: 'a', 'b'` 
https://github.com/lunet-io/scriban/blob/master/doc/liquid-support.md#known-issues
- Remove '-' from liquid operator  brackets `{%- comment -%}` -> `{% comment %}`   

- replaced interpolation in localization resources from Liqud expression to string format 
**From**
en.default.json
```JSON
...
 "less": "Under {{ less }}"
...
```
**To**
```JSON
...
  "less": "Under {0}",
...
```

**Comment by ilyawzrd** [comment]
One more change:

- Scriban doesn't have support for `else` tag inside `for` loop. I think we should check object with `.empty?` before declaring `for` loop.
Example:
`{% if collection.products.empty? %}
       <div class="grid-item">
         <p>{{ 'collections.general.no_matches' | t }}</p>
       </div>
     {% else %}
         {% for product in collection.products %}
           {% include 'product-list-item' %}        
         {% endfor %}
     {% endif %}
`

**Comment by trueboroda** [comment]
`forloop` object doesn't exist into context of the scriban `for` loop. Its behavior must be implemented using  variables and math functions.

**Comment by trueboroda** [comment]
For static content such us pages and blogs root routing does not work. For example we have to use '/pages/about_us'  instead of '~/pages/about-us'. In that case page rendering is ok. This should be fixed.

**Comment by trueboroda** [comment]
An realizaion of liquid "date" filter don't support strftime format. It is necessary to use a standard format for the .net framework. https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by trueboroda** [comment]
The WorkContext property`current_page` has a completely different meaning than before in ranges of shopify work context . Previously, this meant the current page number in pagination. The property now stores the object of the current static page.

**Comment by trueboroda** [comment]
String contains operator must recieve only sinqle quotes string as argument. For example: 
`{%if article.excerpt contains "<iframe" %}` is not worked.
`{%if article.excerpt contains '<iframe' %}` is worked.

**Comment by trueboroda** [comment]
Scriban do not understand HTML comment as text that don't need to parse. To avoid parsing such comments we need to wrap them by liquid comment tag. 
`<!--<p>{{some_var}}</p>-->` - occur error.
Wrapped by liquid comment tag is Ok. 
`` - occur error.

**Comment by trueboroda** [comment]
To obtain the necessary links from `linkslist` object of data context, we must use an indexer with the name of the list, than just to use the named property of the  `linkslist` context object as befor.
`{% for link in linklists.main-menu %}` -> `{% for link in linklists['main-menu'].links %} `

**Comment by trueboroda** [comment]
We must to avoid a situation when a part of the liquid excpression can be 'null'. In that case we should use a previusly checking for 'null' value, after that we can perfom any expression. 
See the following examples.

**Comment by trueboroda** [comment]
For checking var to `null` value we need use direct usage var as condition operand. 
For example  `{%if article.excerpt %}`.  null == false; not null == true.  Internal function  `empty?` (`article.excerpt.empty? == true`) is not work for such cases, as well as comparing with internal `empty` var (`article.excerpt == empty`).

**Comment by trueboroda** [comment]
Significantly changed the names of objects responsible for working with the faceted search (sidebar filters).
`collection.all_tags.groups` => `product_search_result.aggregations`.
`current_tags` => `current_product_search_criteria.terms`.
For more understanding see code of sidebar filters snippet's befor on dotLiquid and after migration on Scriban.
[dotLiquid markup](https://github.com/VirtoCommerce/vc-theme-default/blob/v1.3.3/snippets/collection-sidebar.liquid).
[Scriban markup](https://github.com/VirtoCommerce/vc-theme-default/blob/features/scriban-migration/snippets/collection-sidebar.liquid).

**Comment by trueboroda** [comment]
Now the Json liquid filter use Camal Case naming strategy instead of Cebab Case strategy.

**Comment by ilyawzrd** [comment]
We have to write conditional expressions in one line,otherwise we will get an error "Expecting EOL"
`{% elsif page.url contains 'glossary/magento-alternatives' or page.url contains 'glossary/best-ecommerce-platforms' or page.url contains 'glossary/shopify-alternatives' or page.url contains 'glossary/nopcommerce-alternative' or page.url contains 'glossary/elastic-path-alternatives' or page.url contains 'glossary/znode-alternatives' or page.url contains 'glossary/3dcart-alternatives' or page.url contains 'glossary/demandware-alternatives' or page.url contains 'glossary/episerver-alternatives' %}`

**Comment by tatarincev** [comment]
This issue is migrated to Wiki article [How to: Migrate theme to new 4.х storefront version](https://github.com/VirtoCommerce/vc-storefront-core/wiki/How-to:-Migrate-theme-to-new-4.%D1%85-storefront-version-powered-by-Scriban-template-engine)

Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.0.0.0
