### ISSUE TITLE
Error when loggin into b2b online demo

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#190]
### Expected behavior
Should be able to login.

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/51497152-0db83300-1d77-11e9-982e-3de4ab4f8e16.png)

### Steps to reproduce
1. Go to https://demo.virtocommerce.com/B2B-store/
2. Login as james@org1.com
3. Error above appears.

**Comment by tatarincev** [comment]
I can't reproduce from my side. Were you have any some prerequisites actions, some products in cart or previously logged as other user?
![issue-with-sign-in-b2b](https://user-images.githubusercontent.com/7566324/51516005-6c84b780-1e1e-11e9-98be-23b6c4c4db1c.gif)

**Comment by Woland2k** [comment]
Yeah, works now, maybe something was changed on demo site.
