### ISSUE TITLE
Displays incorrect data inside b2b store

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#191]
### Expected behavior
Change password screen

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/51565128-f7c57380-1e45-11e9-9af1-2638f5663541.png)

### Steps to reproduce
1. Go to b2b admin
2. Click "change password"
3. I see digital ship.

**Comment by eMazeika** [comment]
I believe it's fixed already. Can check and close?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
