### ISSUE TITLE
Scriban: shouldn't crash the whole site if template syntax is wrong

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#193]
### Expected behavior
Should display a message with something like liquid template error. Should have a setting that allows to either crash when syntax error encountered or display inline parsing error.

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/51647743-d9897180-1f32-11e9-92c0-54dd33e4e71e.png)

**Comment by tatarincev** [comment]
Currently, for all these errors the error page contains a line and template name where this error has happened
