### ISSUE TITLE
When static resource not found obscure error is given

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#194]
### Expected behavior
Should explain that static bundle file doesn't exist instead of trying to read stream from non-existent resource and give the not so obvious error 

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/51647956-aabfcb00-1f33-11e9-91a2-d17838955999.png)

### Steps to reproduce
1. Remove static resources from the theme (or download github default theme)
2. Open the storefront.

### Technical details:
Error occurs when AppendVersion filter is calculating hash for non-existent asset (e.g. for liquid template {{ 'bundle/styles.css' | static_asset_url | append_version | stylesheet_tag }} when bundle/styles.css does not exist). 
In that case we do not need to throw the error, AppendVersion filter should not apply any version. Page should load, and we will see reasonable error about non-existent resource in browser console.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.8
