### ISSUE TITLE
Migrate Storefront to NET Core 2.2.1

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront-core#205]
Storefront projects should be migrated to [NET Core 2.2.1](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.1-windows-x64-installer)

**Comment by alireza-salehi** [comment]
is InProcess hosting model supported? or we need to use default OutOfProcess hosting model?

**Comment by yecli** [comment]
Yes, now InProcess hosting model is not supported, you could only use default OutOfProcess.

**Comment by yecli** [comment]
@alireza-salehi We are not planning to add support of InProcess hosting model ourselves for now as ASP.NET Core web server throughput is not the performance bottleneck by far. We are not even close to millions request per second which [ASP.NET Core could afford](https://www.ageofascent.com/2019/02/04/asp-net-core-saturating-10gbe-at-7-million-requests-per-second/).

Current problem is that when using InProcess model [IHostingEnvironment.WebRoot](https://github.com/VirtoCommerce/vc-storefront-core/blob/d35da43af3fbe5259b0ef693b50982eab0b7eb5f/VirtoCommerce.Storefront/Extensions/HostingEnviromentExtension.cs#L10) path is null, and Path.GetCurrentDirectory() targets to iisexpress or another hosting process. We need to get site wwwroot folder path.

If you want to find the solution, you are welcome to create a pull request.

**Comment by yecli** [comment]
Migration to NET Core 2.2.1 released in [v3.2.9](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.9)
