### ISSUE TITLE
400 Bad Request for some POST requests to API and form action

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#209]
The problem:
In some cases storefront is responded with 400 errors for Api and form action POST requests.

How to reproduce:
Open https://demo.virtocommerce.com/Electronics/en-US/account/login in Chrome browser in incognito mode with open development console
Try to login 
Got 400 error

**Comment by avas** [comment]
We encountered this issue on HNG, too. In our case, this was happening because of antiforgery token mismatch. However, for some reason this started to happen less often since Chrome 72.
