### ISSUE TITLE
The user contact organizations were deleted, except for one, after a forgot password operation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#215]
Prerequisites:
Exists contact with associated user that has more than one associated organizations
### Steps to reproduce
1. Request reset password on the storefront (login form -> click forgot password)
2. Navigate to link from email received as result of previous action and define the new password
3. Only one organization left for contact that associated with user, all other organizations references were deleted

**Comment by yecli** [comment]
Released in [v3.2.9](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.9)
