### ISSUE TITLE
Error uploading new theme.

### ISSUE THREAD

**Issue by getmansky** [VirtoCommerce/vc-storefront-core#217]
Version info:

* Browser version: Google Chrome 72.0.3626.119
* Platform version: Windows 10
* Storefront version: 3.2.8

When try to upload theme as zip-file, get error. Answer code is 401 with message {"message":"Authorization has been denied for this request."}

### Expected behavior
Adding of uploaded theme to content.

### Actual behavior
Error uploading theme.

### Steps to reproduce
1. Log out of platform.
2. Log in again.
3. Navigate to Content -> Themes
4. Click Upload.
5. Drag-and-drop or select zip-file of theme.
6. Get error.

![image](https://user-images.githubusercontent.com/47969278/53487171-e5b99f00-3a9b-11e9-86e3-ddfc84979a68.png)

**Comment by eMazeika** [comment]
duplicated by https://github.com/VirtoCommerce/vc-platform/issues/1577

**Comment by yecli** [comment]
Fixed in VirtoCommerce/vc-platform#1577
