### ISSUE TITLE
Add gift reward support to storefront.

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront-core#222]
Need to handle [Gift reward](https://github.com/VirtoCommerce/vc-module-dynamic-expressions/blob/ab84b2159b1cbf4979da3634d5b94f8243258866/VirtoCommerce.DynamicExpressionsModule.Data/Promotion/Rewards/RewardItemGiftNumItem.cs) on storefront.

Platform class for gift reward - [GiftReward](https://github.com/VirtoCommerce/vc-module-core/blob/025ae6e5722f49033899122994c9a65aad22d5fe/VirtoCommerce.Domain/Marketing/Model/Promotions/Rewards/GiftReward.cs).

Need to add customized gift to cart when GiftReward could be applied.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-96
