### ISSUE TITLE
Use Google Map for Checkout Address fields

### ISSUE THREAD

**Issue by kamilgarey** [VirtoCommerce/vc-storefront-core#234]
I offer in Checkout for address fields use not predifined JSON but Google Maps.

This is the example (one can check in JsFiddle) https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform#try-it-yourself

And we don't need to change interface - we can use exists fields https://stackoverflow.com/questions/8282026/how-to-limit-google-autocomplete-results-to-city-and-country-only

We can limit language https://stackoverflow.com/questions/16835727/limit-places-autocomplete-to-a-certain-language

and limit locations https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries

Downsides:
1) We need to work with ApiKey. This can be done to work with google map from the box https://stackoverflow.com/questions/39329874/googlemaps-api-key-for-localhost
2) If there are a lot of requests we(customer) need to pay Google

**Comment by kamilgarey** [comment]
Since I was used Google Map it become more difficult. https://cloud.google.com/maps-platform/pricing/

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
