### ISSUE TITLE
Duplication of address

### ISSUE THREAD

**Issue by adminoren** [VirtoCommerce/vc-storefront-core#240]
Version info: 
- Storefront version: 3.2.11 scriban-migration branch

### Expected behavior
User has one address stored in the database. Request to URL /storefrontapi/account?t=... should return one address in fields addresses and contact.addresses of response.
### Actual behavior
![2019-04-16_17-09-06](https://user-images.githubusercontent.com/38526853/56209044-02219300-606c-11e9-9097-bc69605f01c6.png)

**Comment by tatarincev** [comment]
@adminoren This is  logic  by design to merge  Contact  and  User properties  for API methods that return User. This logic is left for backward compatibility with old themes. You might  disable this Json converter in your solution if this behavior is not desired.
