### ISSUE TITLE
Problems with GetInvoice method

### ISSUE THREAD

**Issue by adminoren** [VirtoCommerce/vc-storefront-core#242]
Method storefrontapi/orders/{orderNumber}/invoice is insecure. When a user knows how the numbers of orders are created he can download invoices for orders of other users.
Maybe it's better to change this method and create an invoice by orderId instead of orderNumber?

**Comment by artem-dudarev** [comment]
It's better to check if current user has acces to the requesting order.

**Comment by yecli** [comment]
Released in [v3.2.10](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.10).
