### ISSUE TITLE
X-Frame-Options

### ISSUE THREAD

**Issue by cqkisyouq** [VirtoCommerce/vc-storefront-core#245]
I use it on my other sites iframe
When did you add the following paragraph in the response header ?
X-Frame-Options: SAMEORIGIN

**Comment by yecli** [comment]
There is no such header in storefront responses.
If you meant this header presence in Platform API requests - it was added to avoid clickjacking. [commit](https://github.com/VirtoCommerce/vc-platform/commit/ba187280ff0395adbf5ae3831516d6c525bcc1f8).
It is configurable in [web.config](https://github.com/VirtoCommerce/vc-platform/blame/6431aaee0e54bf073adaf864b2a58ca9066ae744/VirtoCommerce.Platform.Web/Web.config#L170). You need to understand the risks when changing/removing it.
