### ISSUE TITLE
"Featured" sorting is not working properly

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront-core#248]
"Featured" sorting is now working properly.

Set Priority "1" for the product, when others have 0.
![image](https://user-images.githubusercontent.com/15610352/56502591-46110e00-652c-11e9-880c-9bf19439fcbf.png)

### Expected behavior
When using Featured sorting, Product with higher priority should appear at the beginning of the list on the storefront. Products with the same priority should be sorted in alphabetical order.

### Actual behavior
Products are not sorted as expected.

**Technical details**:
Need to pass priority (desc) and name sort infos to platform API.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/edit/v4.0.0.0
