### ISSUE TITLE
SetCompatibilityVersion(CompatibilityVersion.Version_2_2) causes routing error

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-storefront-core#252]
Changing MVC application compatibility version to 2.2 `SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`
causes following error:
InvalidOperationException: Cannot use 'VirtoCommerce.Storefront.Routing.SlugRoute' with Endpoint Routing.
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)

InvalidOperationException: Cannot use 'VirtoCommerce.Storefront.Routing.SlugRoute' with Endpoint Routing.
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)
VirtoCommerce.Storefront.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs
…

Technical details:
https://github.com/kobake/AspNetCore.RouteAnalyzer/issues/19

+

Need to remove specific ASP.NET.Core versions from csproj files.

**Comment by AliveMen** [comment]
Any implementing IRouter is currently not compatible with endpoint routing.
https://github.com/aspnet/AspNetCore/issues/4221
and recommended to use `services.AddMvc(options => options.EnableEndpointRouting = false)`
Instead of this we can use default Route type and linkGenerator 
https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-0-preview1-endpoint-routing/

**Comment by yecli** [comment]
Current PR fixes the problem, so it could be merged.
But indeed we need to add Middleware with `LinkGenerator` like in [link above](https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-0-preview1-endpoint-routing/) to implement MapSlugRoute functionality to switch to 2.2 routing system.

**Comment by yecli** [comment]
Released in [v3.2.10](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.10).
