### ISSUE TITLE
Full name field doesn't change when editing first/last name

### ISSUE THREAD

**Issue by ekutasina** [VirtoCommerce/vc-storefront-core#258]
**Stage:** https://demo.virtocommerce.com
**Devices:** All 
**Browser:** Chrome, Chrome mobile
**User:** maked/SAshok171

**Steps:**
1. Open https://admin-demo.virtocommerce.com use data admin/store
2. Click "Contact"
3. Find "Alex Tzykin"
4. Check Full name field
5. Open storefront in other tab
6. Sign in
7. Open https://demo.virtocommerce.com/Electronics/en-US/account#/profile
8. Change first name and last name
9. Click Update
10. Open first tab in browser
11. Reload page
12. Find Alex Tzykin
13. Check Full name field

**Actual result:** Data in Full name fields is was not changed 
**Expected result:** Data in field Full name has been changed

**Comment by yecli** [comment]
Technical details:
Need to generate FullName on [account update](https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Controllers/Api/ApiAccountController.cs#L396) the same way it is done on creation.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.0.0.0
