### ISSUE TITLE
Theme location discovery reporting is not implemented correctly

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#26]
The discovery paths of where template is resolved should be added at the time of resolution instead of after the fact using: _liquidThemeEngine.DiscoveryPaths.

Currently "_liquidThemeEngine.DiscoveryPaths" is simply a static method that is calculated based on preconfigured discovery folders paths. Instead find template should return a view object which when view view is not found contains collection of absolute paths view was searched in.

**Comment by tatarincev** [comment]
No longer relevant from the new Storefront versions since 4.0.0 version
