### ISSUE TITLE
UserGroups, CurrentPricelists should be part of cacheKey in SearchProductsAsync

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront-core#266]
Version info: 
- Storefront version: v3.2.9

### Expected behaviour
Display different product list for the different customer if they have different either UserGroups or CurrentPricelists 

### Actual behaviour
The customer sees the wrong product list from the caches. 

### Steps to reproduce
1. Create customer A and customer B with different either UserGroups or CurrentPricelists. Customize the catalogue to see a different set of the products on either UserGroups or CurrentPricelists.
2. Log in with customer A and open category page, see one set of the products
3.  Log in with customer B and open category page, see the same (wrong) set of the products

https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs#L204

https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs#L161

https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Domain/Catalog/CatalogConverter.cs#L163

**Note:** I think we should remove workContext from Converters or be careful with cacheKey 

**Note:** Same problem can occur for other cacheKey. Need to review

**Comment by OlegoO** [comment]
I see that @tatarincev fixed DEV for UserGroups 
https://github.com/VirtoCommerce/vc-storefront-core/commit/6d83b4e7f6949da097a18f2c4da14c7c2ea8e8cb

but not for PriceLists

**Comment by yecli** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.11
