### ISSUE TITLE
 EF concurrency error on cart save

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-storefront-core#267]
Seeing an EF concurrency error on Cart Save

Version info: 
- Browser version:  all
- Platform version: V 2.13.21
- Storefront version:V 1.0

This code is controlled within the VirtoCommerce.Platform.Core and VirtoCommerce.Platform.Data modules.  Currently we have V 2.13.21.   Here is the exception details.  We are seeing this pretty often.  12 times in the last 24 hours but it carries on all the time (not limited to the past 24 hours).   Please provide insight/fix on this error.

Operation returned an invalid status code 'InternalServerError'
{"message":"An error has occurred.","exceptionMessage":"Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.\r\nStore update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.","exceptionType":"System.ServiceModel.FaultException","stackTrace":"   at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex)\r\n   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository)\r\n   at VirtoCommerce.CartModule.Data.Services.ShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts)\r\n   at JBS.Virto.CartExtensions.Services.ExtShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts) in C:\\agent\\_work\\2\\s\\Modules\\JBS.Virto.CartExtensions\\JBS.Virto.CartExtensions.Web\\Services\\ExtShoppingCartServiceImpl.cs:line 71\r\n   at VirtoCommerce.CartModule.Web.Controllers.Api.CartModuleController.<Update>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"}

**Comment by yecli** [comment]
First thing that needs to be checked is whether described error repeats on latest platform/modules and storefront versions, as I can see very old versions are used.

**Comment by emathavan** [comment]
Thanks Yecli.   We are gradually deploying the upgrades to get to the most current version of the storefront and platform modules, but it will take some time. 

Do you have any insight on a new exception occurring in Prod Storefront and know if a dll fix has been pushed out to resolve it? This is occurring in 2 places:

22 times since 6/6/2019

1.       Rental modal window in OE reaching out to storefront

The cart is retrieved (for the sessionid)
Changes made to cart
Cart is saved and we get an exception…
Operation returned an invalid status code 'InternalServerError'

{"message":"An error has occurred.","exceptionMessage":"An error occurred while updating the entries. See the inner exception for details.\r\nAn error occurred while updating the entries. See the inner exception for details.\r\nViolation of PRIMARY KEY constraint 'PK_dbo.Cart'. Cannot insert duplicate key in object 'dbo.Cart'. The duplicate key value is (777d6355-e98c-4b3c-bc4c-bfa357e483f8).\r\nThe statement has been terminated.","exceptionType":"System.ServiceModel.FaultException","stackTrace":"   at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex)\r\n   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository)\r\n   at VirtoCommerce.CartModule.Data.Services.ShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts)\r\n   at JBS.Virto.CartExtensions.Services.ExtShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts) in C:\\agent\\_work\\2\\s\\Modules\\JBS.Virto.CartExtensions\\JBS.Virto.CartExtensions.Web\\Services\\ExtShoppingCartServiceImpl.cs:line 71

2.       Saving Payments on Checkout in Storefront

Cart is loaded
Changes made
Cart is saved and we get these exceptions…
An error occurred while updating the entries. See the inner exception for details.

An error occurred while updating the entries. See the inner exception for details.

Violation of PRIMARY KEY constraint 'PK_dbo.CartPayment'. Cannot insert duplicate key in object 'dbo.CartPayment'. The duplicate key value is (33e1a710d4054535aca137b13ded4966).

The statement has been terminated.


Operation returned an invalid status code 'InternalServerError'

{"message":"An error has occurred.","exceptionMessage":"An error occurred while updating the entries. See the inner exception for details.\r\nAn error occurred while updating the entries. See the inner exception for details.\r\nViolation of PRIMARY KEY constraint 'PK_dbo.CartPayment'. Cannot insert duplicate key in object 'dbo.CartPayment'. The duplicate key value is (33e1a710d4054535aca137b13ded4966).\r\nThe statement has been terminated.","exceptionType":"System.ServiceModel.FaultException","stackTrace":"   at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex)\r\n   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository)\r\n   at VirtoCommerce.CartModule.Data.Services.ShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts)\r\n   at JBS.Virto.CartExtensions.Services.ExtShoppingCartServiceImpl.SaveChanges(ShoppingCart[] carts) in C:\\agent\\_work\\2\\s\\Modules\\JBS.Virto.CartExtensions\\JBS.Virto.CartExtensions.Web\\Services\\ExtShoppingCartServiceImpl.cs:line 71


Somehow it seems that on the Platform side it’s not retrieving the cart (or payment) correctly from the DB just prior to the update (thinks it is a new record) and tries to insert to the DB and an exception is thrown indicating that it already exists.  The error is occurring in exactly the same place as the “Store update, insert, or delete statement affected an unexpected number of rows (0)” error we have also been seeing that I have now not seen since 6/4/2019

**Comment by yecli** [comment]
Hi Emathavan, 
Unfortunately I do not have info on facing these exception recently.

Don't you have some customizations on modules or storefront? Specific steps to reproduce stable on pure platform/storefront latest versions would be very useful for investigation.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
