### ISSUE TITLE
View is searched in incorrect paths and full paths are not displayed

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#27]
Currently views are searched inside the following folders: 

Themes/Clothing/default/templates
Themes/Clothing/default/snippets
Themes/Clothing/default/layout
Themes/Clothing/default/assets

The view like "index.liquid" should never be searched in any folder besides "templates". 

Same goes with snippets (includes inside liquid), they should only be searched inside "snippets" folder. And layouts should only be seached inside "layout".

**Comment by tatarincev** [comment]
Fixed in the new Storefront since 4.0 version powered on Scriban template engine
