### ISSUE TITLE
User cant purchase product that was previously unavailable

### ISSUE THREAD

**Issue by dvs39** [VirtoCommerce/vc-storefront-core#279]
Please provide detailed information about your issue, thank you!

Version info: 
- Platform version: 2.13.47
- Storefront version: 4.0.0

### Steps to reproduce
1. As customer, go to storefront and add ProductA to cart
2. As admin, set ProductA.IsBuyable = false
3. As customer refresh page and make sure that cart now in invalid state
4. As admin, set ProductA.IsBuyable = true

### Expected behavior
When ProductA.IsBuyable = true user should be able to proceed to checkout

### Actual behavior
When ProductA.IsBuyable = true user is not able to proceed to checkout

Seems like CartBuilder.ValidateCartItemsAsync() never set lineItem.IsValid to true

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
