### ISSUE TITLE
How to replace the memory cache here with Redis cache

### ISSUE THREAD

**Issue by ghd258** [VirtoCommerce/vc-storefront-core#285]
How to replace the memory cache here with Redis cache
` public static class MemoryCacheExtensions
    {
        private static ConcurrentDictionary<string, object> _lockLookup = new ConcurrentDictionary<string, object>();
        public static async Task<TItem> GetOrCreateExclusiveAsync<TItem>(this IMemoryCache cache, string key, Func<MemoryCacheEntryOptions, Task<TItem>> factory, bool cacheNullValue = true)
        {
            if (!cache.TryGetValue(key, out var result))
            {
                using (await AsyncLock.GetLockByKey(key).LockAsync())
                {
                    if (!cache.TryGetValue(key, out result))
                    {
                        var options = cache is IStorefrontMemoryCache storefrontMemoryCache ? storefrontMemoryCache.GetDefaultCacheEntryOptions() : new MemoryCacheEntryOptions();
                        result = await factory(options);
                        if (result != null || cacheNullValue)
                        {
                            cache.Set(key, result, options);
                        }
                    }
                }
            }
            return (TItem)result;
        }

        public static TItem GetOrCreateExclusive<TItem>(this IMemoryCache cache, string key, Func<MemoryCacheEntryOptions, TItem> factory, bool cacheNullValue = true)
        {
            if (!cache.TryGetValue(key, out var result))
            {
                lock (_lockLookup.GetOrAdd(key, new object()))
                {
                    if (!cache.TryGetValue(key, out result))
                    {
                        var options = cache is IStorefrontMemoryCache storefrontMemoryCache ? storefrontMemoryCache.GetDefaultCacheEntryOptions() : new MemoryCacheEntryOptions();
                        result = factory(options);
                        if (result != null || cacheNullValue)
                        {
                            cache.Set(key, result, options);
                        }
                    }
                }
            }
            return (TItem)result;
        }`

**Comment by tatarincev** [comment]
I think what the better explicitly use `IDistributedCache` abstraction in place instead of completely substitute `InMemory` cache to distributed one. Because there are the  potential  problems with serialization/deserialization of cached data.
We have some plans regarding the implementation of a distributed cache in storefront, but, unfortunately, I can’t say the exact dates when this will be done.

**Comment by eMazeika** [comment]
was this released?

**Comment by tatarincev** [comment]
In the https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0 was introduced the Hybrid cache mode. It allows keeping a local cache in sync state between multiple storefront instances.  I guess it will be a suitable solution for you.
