### ISSUE TITLE
Nuget updates

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#288]
With regards to package updates I see VC storefront core most of the time lags behind new package releases, especially I'd like to see more frequent .NET Core package updates for example at the moment of writing updating to 2.2.6.

https://devblogs.microsoft.com/dotnet/net-core-july-2019/

Usually I do it myself in my own fork but I have to keep repeating that everytime I try to bring my fork up to date with this repo.

**Comment by tatarincev** [comment]
Thanks for valuable notice, we cannot always keep up with MS  updates, but you always can help to project  with your contribution :)

**Comment by brgrz** [comment]
With a PR? It would have to be merged very as soon as possible to be of value, which many times doesn't happen.

**Comment by tatarincev** [comment]
I promise you that I'll  merge your PR ASAP

**Comment by brgrz** [comment]
:)

**Comment by brgrz** [comment]
actually I just noticed that if I reference asp.net core packages by version, specifying Version="2.2.6" I get a warning saying I shouldn't do that.

I'm currently trying to figure out why the Storefront.Models references 2.2.2 while the other three projects reference 2.2.0 and how did that happen, since in .csproj they all don't specify a version

but nuget updater prompts me to consolidate, weird

**Comment by brgrz** [comment]
Apparently as per this thread it is enough to install runtime&hosting patches on the servers and not necessary to update the apps between major/minor pair updates.

https://stackoverflow.com/questions/54842747/how-to-update-aspnetcore-from-2-2-0-to-2-2-2

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
