### ISSUE TITLE
for API need to return status code 401 when cookie session is expired

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-storefront-core#291]
- Platform version: 2.13.46
- Storefront version: 4.0.0.0

### Expected behavior
When auth cookie session time expired API methods must return HTTP Status code **401**. 

### Actual behavior
Now, in this case, returned **200 Ok**. Response body contains HTML text of page **'/Account/Login'**.  That is, the backend returns us a MVC view of login page instead of 401 Code.

### Steps to reproduce
1. Reduce CookieAuthenticationOptions.ExpireTimeSpan param of appsetings.json  to convenient for test purpose. For example to 2 min.
2. Start storefront with any theme.
3. Go to the page where angular app of theme call some API method.
4. Open browsers console on tab network. After the tuned cookie time is expired do page refresh with F5 and see any api calling result response. The response will contain all as described above.

**Comment by trueboroda** [comment]
Also, need to return 403 when forbidden.

**Comment by tatarincev** [comment]
Fixed by this commit https://github.com/VirtoCommerce/vc-storefront-core/commit/3c93253a20e49f158b9b2dd314227a33997b7ee2

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
