### ISSUE TITLE
Unexpected redirect to Login page when cookies expired 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#292]
**Expected Behavior**
User continues browse as anonymous unless an anonymous access is not restricted for store settings
**Actual Behavior**
The login page is displayed.

**Hot to reproduce**

- In  `appsettings.json`  set  `CookieAuthenticationOptions.ExpireTimeSpan` = "00:05:00"
- Run storefront 
- Open index  page (http://localhost:2803/)  the browser with  incognito mode   
- Log in as any user
- Open any other  tab in browser  Google for example
- Close  browser tab with index page
- Wait 5 min
- Open  the storefront  index page again (http://localhost:2803/)
- Login page will open  **Not expected behavior**

**Comment by blazemachine** [comment]
Now is appearing a new not indicated error that have a code 400 (this info from ErrorController). Screenshot attached below.
![image](https://user-images.githubusercontent.com/43133766/64512106-1908a080-d2ff-11e9-81f4-164cda03e824.png)

**Comment by blazemachine** [comment]
Successful logins were happened too, but error is appearing in overwhelm cases.

**Comment by blazemachine** [comment]
The problem that was described before is appear only at set low value for ExpireTimeSpan (5-10 seconds for example).

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
