### ISSUE TITLE
Fix RelatedProducts functionality

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront-core#298]
Version info:
- Storefront version: latest

### Expected behavior
RelatedProducts collection available in theme

### Actual behavior
RelatedProducts collection is missing after code migration to scriban

**Comment by yecli** [comment]
@trueboroda Are you familiar with this problem?

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.2
