### ISSUE TITLE
Fix user profile management

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront-core#300]
Version info: 
- Storefront version: latest

### Expected behavior
Customer should be able to update his profile, including first name.
### Actual behavior
POST storefrontapi/account 500 Internal Server Error {"message":"An error has occurred.","exceptionMessage":"Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.\r\nThe FullName field is required."
### Steps to reproduce
1. try changing FirstName from MY ACCOUNT

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.0.2
