### ISSUE TITLE
Wrong redirection to login page when store is not default

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-storefront-core#307]
Scenario1
1. Set "Allow anonymous user for store" to false for any not default store (e.g. "Clothing")
2. Try to open this store. You`ll be redirected to the login page of the default store. 

Scenario 2
1. Set "Allow anonymous user for the store" to false for any not default store (e.g. "Clothing")
2. add store path segment to bad login path (e.g. below on image)
![image](https://user-images.githubusercontent.com/13153256/65683333-ab31d800-e065-11e9-8466-579a535b0a99.png)
3. Click logout. You`ll be redirected to the login page of the default store. 

Scenario 3
The same when session time is expired.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
