### ISSUE TITLE
User/password recovery works strange

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#308]
Recovery email can be anything, even something like xx@xx.xx. 
And the system says: "An email with your user name has been sent to your address". Even if SMTP unavailable.

**Comment by artem-dudarev** [comment]
The message should always be the same to prevent email addresses harvesting.
Anonymous user should not be able to find out if specific email address or user name is registered in the system.

**Comment by akak1977** [comment]
Ok. Anyway I thing we need to check SMTP presence at all, and catch another system errors.
