### ISSUE TITLE
Too many EvaluateTaxes requests

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#309]
In StoreFront add to cart any product. This action invoke TaxModel Controller Evaluate Taxes method many times.
Also EvaluateTaxes called when we search product in Storefront

**Comment by AliveMen** [comment]
**How to repeat multiple requests to TaxApi:** 
	Install the Avalara Tax module.
	Select installed tax provider in a store settings.
	Turn on the “Calculate taxes” options in the Platform.Settings.Taxes blade.
        Run Storefront and add any item to a Cart or text to search box. 


**When we add an item to a cart we see 3 API calls:**

1.  Tax calculated for product and it’s variations 
https://github.com/VirtoCommerce/vc-storefront-core/blob/ff774a1e318d702a5203ae5aaa6ef1a5c7a499da/VirtoCommerce.Storefront/Controllers/Api/ApiCatalogController.cs#L40
2. When add an item cart 
https://github.com/VirtoCommerce/vc-storefront-core/blob/ff774a1e318d702a5203ae5aaa6ef1a5c7a499da/VirtoCommerce.Storefront/Controllers/Api/ApiCartController.cs#L96
3. When saving cart 
https://github.com/VirtoCommerce/vc-storefront-core/blob/fac8bd65fcb2339882ed92f707011e9c64b9cfcb/VirtoCommerce.Storefront/Domain/Cart/CartBuilder.cs#L465


**Two api calls when search an item :**
1.
https://github.com/VirtoCommerce/vc-storefront-core/blob/ff774a1e318d702a5203ae5aaa6ef1a5c7a499da/VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs#L171
2. When chouse item from search list
https://github.com/VirtoCommerce/vc-storefront-core/blob/ff774a1e318d702a5203ae5aaa6ef1a5c7a499da/VirtoCommerce.Storefront/Domain/Catalog/CatalogService.cs#L78

**Comment by trueboroda** [comment]
For the Fixed Tax provider it was corrected. For other providers using external services like Alvara tax provider, it must be so. Tax evaluation should use API calling each time when it is needed. In the second case, API-calling is minimizing by сache using.
