### ISSUE TITLE
Coupon doesn't work if has catalog condition with parent category

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#310]
like Televisions -> LG

![image](https://user-images.githubusercontent.com/9972421/65745272-94968a00-e114-11e9-8c0b-5639e8df6839.png)
this is bug from storefront side
![image](https://user-images.githubusercontent.com/9972421/65745325-cad40980-e114-11e9-917a-8e822951d392.png)

**Comment by yecli** [comment]
Release https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.4
