### ISSUE TITLE
Each of created adresses shown twice

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#311]
1. Login in storefront as bomba89@example.com
2. Try to create address.
3. Then: newly entered address will shown twice in list:
![image](https://user-images.githubusercontent.com/9972421/65747771-b9dac680-e11b-11e9-9dec-2e31bfb6aad5.png)

It does not depend on platform version (v2/v3)
Debug in LiquidThemedView.RenderInternalAsync shows duplicated addresses in scriptObject. (LiquidThemedView.cs near line 79).

**Comment by AliveMen** [comment]
We had used Newtonsoft.Json.Merge without any setting. Default value is "Concat" that means - Concatenate arrays. Now using "Merge"  - Merge array items together, matched by index.

**Comment by yecli** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.2
