### ISSUE TITLE
Recently added address could not be removed

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#312]
Add address in address list of account properties, then try to delete one:
![image](https://user-images.githubusercontent.com/9972421/65748625-d2e47700-e11d-11e9-9512-36457ffba23b.png)
Nothing happened except some frame flickering.
It does not depend on platform version (v2 or v3).

**Comment by AliveMen** [comment]
Has been fixed in task https://github.com/VirtoCommerce/vc-storefront-core/issues/311
