### ISSUE TITLE
Facet search group prices: wrong place of decimal separator 

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#313]
Decimal separator in prices have wrong place:
![image](https://user-images.githubusercontent.com/9972421/65854012-c148dc80-e374-11e9-9106-d2fa7468abd3.png)

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-theme-default #111](https://github.com/VirtoCommerce/vc-theme-default/issues/111) via [**ZenHub**](https://www.zenhub.com/)
