### ISSUE TITLE
The index page will be not found without final slash symbol '/' for not default store

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-storefront-core#316]
How it's now.
Try open http://demo.virtocommerce.com/clothing. 
Result: 'Not found page' will be showed. 
Expected result: Index page is showed.

![image](https://user-images.githubusercontent.com/13153256/66196943-0f761c80-e6a2-11e9-9ff5-a3cff506fbc2.png)

If we add the final slash symbol
Try open http://demo.virtocommerce.com/clothing/
Result: Index page is showed.
![image](https://user-images.githubusercontent.com/13153256/66196982-21f05600-e6a2-11e9-8c54-3bdf7ba9b760.png)

**Comment by tatarincev** [comment]
@trueboroda  It is behavior by design. 
Here is link to RFC https://www.freesoft.org/CIE/RFC/1630/9.htm
```
If a path of the context locator ends in slash, partial URIs are treated differently to the URI with the same path but without a trailing slash. The trailing slash indicates a void segment of the path.
```
