### ISSUE TITLE
Implement SPA mode for separate store as an option

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-storefront-core#317]
Required:
SPA mode as the option for the concrete store. This can be realized on a platform side. 
In SPA mode storefront should return the index page of Theme when on side of storefront response can`t be found with storefront routing. In this case, the route will be handled on the frontend side by the SPA app's inner routing.  

This is a prototype of implementation: https://github.com/VirtoCommerce/vc-storefront-core/commit/39f648f7ac4a4affd524b7f894d0390786cc2238

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
