### ISSUE TITLE
the cache should be consistent between the different instance of storefronts.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront-core#318]
### Expected behavior
The cache items should be consistent between the different instance of storefronts.

### Actual behavior
Two or more instance. 
Add a product into the cart - one instance
Get the cart from any other instance. 
See the wrong result from the cache.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.0
