### ISSUE TITLE
Ensure that SmtpClient is always configured on demo site

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-storefront-core#321]
SmtpClient information isn't filled on demo site:
* can't test email notification sending from admin-demo
* can't send user invitation from b2b store
* can't reset password, etc.

There is even no warning about that, so seems like a broken functionality.

**Comment by eMazeika** [comment]
any progress?

**Comment by eMazeika** [comment]
https://github.com/VirtoCommerce/vc-content/issues/53

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-111
