### ISSUE TITLE
CartRepository.GetShoppingCartsByIdsAsync called 10 or more times during checkout and order creation

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#327]
Reprosteps:
1. Add breakpoint  at the beginning of CartRepository.GetShoppingCartsByIdsAsync.
2. Run platform and storefront;
3. Attach-debug cart-module to platform process;
4. Try to buy something in storefront;
5. Breakpoint will catch runflow multiple times during checkout, shipping/payment selection

This problem was preliminary investigated by Andrei Nikutin.
Here are his comments :
Its storefront problem. I disable storefront cache and it make too many requests to platform. I think its a problem, and its needed to check more deeply. Need to create issue for storefront project.
for example: to many taxes/search requests, for every available store (but I worked only with one store)
![image](https://user-images.githubusercontent.com/9972421/67670713-50f2a280-f996-11e9-9118-20c029536cd3.png)

**Comment by yecli** [comment]
Please see #309

**Comment by trueboroda** [comment]
Now information about the current tax provider is loaded with the store model. And there is no need to make a request in every place.  For fixed tax providers, the tax calculation was moved to the storefront side.  This solved related to this issue https://github.com/VirtoCommerce/vc-storefront-core/issues/309.
I also want to note that if you disable the cache this is normal behavior when identical requests are repeated several times with any action on the site.
