### ISSUE TITLE
Move changes from Storefront for ASP.NET Core to Storefront for ASP.NET (.NET Framework)

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#33]
We made some changes (like libsasshost usage #2 or replacement of hard coded directory separators #28 or AntiForgery token generation #16) which we may migrate to old storefront

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
