### ISSUE TITLE
Pages are not processed via liquid

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#35]
![image](https://user-images.githubusercontent.com/6369252/33060255-7a2abdf4-ceb9-11e7-8427-a1d9dfdbee1e.png)

On Storefront for full .NET Framework all ok.

**Comment by tatarincev** [comment]
In page need to use `| liquid` filter for  LIQUID templates rendering

**Comment by asvishnyakov** [comment]
@tatarincev Why? It's breaking change. For example, on vc.com it using often, so we will need rewrite a lot of code.

**Comment by tatarincev** [comment]
The content of each static content page is displayed with `page`  view name and with the template usually accessible by this path` templates/page.liquid` in the theme.
Here's an example of this template from the default theme
```
{% include 'breadcrumb' %}
<div class="grid">
  <div class="grid-item large--two-thirds push--large--one-sixth">
    <h1>{{ page.title }}</h1>
    <div class="rte">
      {{ page.content }} <-- liquid  expression which renders page content
    </div>
  </div>
</div>
```
As you can see, this instruction `{{page.content}}` renders the static content of the page, as is.
To render the liquid markup, you need to add the `liquid` filter to this expression `{{page.content | liquid}}`

**Comment by asvishnyakov** [comment]
@tatarincev But why it working in old storefront?

**Comment by asvishnyakov** [comment]
Not a bug
