### ISSUE TITLE
Character Escaping on search bar value. 

### ISSUE THREAD

**Issue by AlexRHo** [VirtoCommerce/vc-storefront-core#361]
When entering a search into the search bar, any searchQuery that includes a special character ie. ' " & etc.... special character is escaped and value no longer is informative to user and looks "ugly". 
removing the escape function on the searchQuery value in the script tag in the search-bar.liquid file seems to make it worse. 
### Expected behavior
Return user's entered search string
### Actual behavior
Return encoded user search string.
### Steps to reproduce
1.Enter any string into search with a special character
![pic1](https://user-images.githubusercontent.com/32780777/71104054-6dca7b80-2178-11ea-9e04-2cdc60a1ef09.jpg)
![pic2](https://user-images.githubusercontent.com/32780777/71104055-6dca7b80-2178-11ea-8e36-556e66867620.jpg)

**Comment by yecli** [comment]
Released (changes in the storefront and in the theme):
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.8
https://github.com/VirtoCommerce/vc-theme-default/releases/tag/v2.1.4
