### ISSUE TITLE
It is impossible to add two or more different products to the cart using bulk order.

### ISSUE THREAD

**Issue by akak1977** [VirtoCommerce/vc-storefront-core#369]
Steps to reproduce:
1. Go to https://demo.virtocommerce.com
2. Click "Bulk order"
3. Enter any existing product SKU in the first "Product SKU" field
4. Enter any existing product SKU in the second "Product SKU" field (different from the first)
5. Click "Add to cart"

Actual result: "Products with following SKUs was not added to cart:" message is displayed.
image-2020-01-15-17-15-35-397.png
![image](https://user-images.githubusercontent.com/9972421/72536019-54ae0b00-389b-11ea-8127-dfdbfd9ac10b.png)

**Comment by yecli** [comment]
Released:
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v4.1.7
