### ISSUE TITLE
Adding item to the cart generates error

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-storefront-core#399]
Can't add item to the cart. Storefront and platform running in linux environment.

Version info: 
- Browser version: 
- Platform version: 3 rc4
- Storefront version: dev-latest

### Expected behavior
Should add item to the cart

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/78409883-b8ed8a80-75bf-11ea-9ec2-98fcc7066691.png)

### Steps to reproduce
1.  If can't replicate, as for docker image configs.

**Comment by Woland2k** [comment]
Any update on this?

**Comment by Woland2k** [comment]
Resolved using the following:

In Chrome do this: Open the developer-tools goto tab Application and in the left pane choose Clear storage. Under the diagram on the right click Clear site data even if the usage shows 0 Bytes used. Do it anyway.

**Comment by akak1977** [comment]
Is it should be closed?
