### ISSUE TITLE
Make the way to specify response group without placing it in URL params

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#47]
Currently, if you want to load some parts of product, you must specify `resp_group` query in URL. We must found the way to specify it in theme.

**Comment by asvishnyakov** [comment]
@OlegoO @IgorisB  If you have any comments about this issue, please, write here

**Comment by asvishnyakov** [comment]
Possible solution: use "| resp_group" liquid filter, constants for every response group and "| plus: " operator for combining response group values.

How it will work:

```
{% assign product_resp_group: item_resp_group.properties | plus: item_resp_group.editorial_review %}
{% for product in collection.products | resp_group: product_resp_group %}
{{ product | resp_group: product_resp_group | json }}
```

```
{% assign category_resp_group: category_resp_group.properties | plus: item_resp_group.seo %}
{% for collection in collection.parents | resp_group: category_resp_group %}
{{ category | resp_group: category_resp_group | json }}
```

**Comment by asvishnyakov** [comment]
@tatarincev How much more time we need to fix it? Requested by client project

**Comment by tatarincev** [comment]
The new syntax to how we can change search criteria for  data queries from Liquid templates
```
{% paginate collection.products by 5 params {"ResponseGroup":"ItemLarge"} %}
```

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
