### ISSUE TITLE
Error with IIS Url Rewrite rule for Redirect

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront-core#50]
### Expected behavior
Redirect to new correct url

### Actual behavior
NullReferenceException: Object reference not set to an instance of an object. with rule

### Steps to reproduce
1. Add a new rewritre rule into IISUrlRewrite.xml
``````````
        <rule name="Redirect Blogs to Blog" stopProcessing="true">
            <match url="^blogs/news/(.+)" />
            <conditions trackAllCaptures="true" />
            <action type="Redirect" url="blog/{R:1}" />
        </rule>
``````````
2. Open https://vc-public-qc.azurewebsites.net/blogs/news/agile-platform

3. Get error 
NullReferenceException: Object reference not set to an instance of an object.

Microsoft.AspNetCore.Rewrite.Internal.IISUrlRewrite.ConditionEvaluator.Evaluate(ConditionCollection conditions, RewriteContext context, BackReferenceCollection backReferences)
Microsoft.AspNetCore.Rewrite.Internal.IISUrlRewrite.IISUrlRewriteRule.ApplyRule(RewriteContext context)
Microsoft.AspNetCore.Rewrite.RewriteMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
VirtoCommerce.Storefront.Middleware.ApiErrorHandlingMiddleware+<Invoke>d__3.MoveNext() in ApiErrorHandlingMiddleware.cs

**Comment by tatarincev** [comment]
In order for this rule to work, just need to delete this line
 ` <conditions trackAllCaptures="true" />`
