### ISSUE TITLE
Invalidate cache when theme changed

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#52]
Version info: 
- Browser version: Chrome 63
- Platform version: 2.13.19
- Storefront version: 3.0.5

### Expected behavior
Storefront cache should be invalidated when theme files changed.

### Actual behavior
Nothing happens when Azure blob provider used. Locally working normal.

**Comment by asvishnyakov** [comment]
@tatarincev @OlegoO We strongly need this feature, please try to make it within Operations as soon as possible

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-storefront-core/releases/edit/v3.0.7
