### ISSUE TITLE
Update AutoRest to latest version

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#54]

**Comment by eMazeika** [comment]
what is this epic about?

**Comment by asvishnyakov** [comment]
@eMazeika I think we may close it because as I remember now vc-storefront-core use 2.x version of AutoRest

**Comment by eMazeika** [comment]
real epic needs subtasks. :)
I've added one, waiting for completion

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
