### ISSUE TITLE
Allow to disable cache

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#56]
Version info: 
- Storefront version: 3.0.5

### Expected behavior
Storefront must provide configuration setting to disable memory cache on storefront.

### Actual behavior
There is no setting for that

**Comment by tatarincev** [comment]
@ksavosteev  Need to move the previous solution what we have in old storefront. https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/Services/ContentBlobProviders/AzureBlobContentProvider.cs#L52

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
