### ISSUE TITLE
Shopping cart line items  sorting does not work   through Liquid

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#61]
Hello. So i've modified the creationtime of order lineitems to be the same as cart. But when i sort them in the notification like this {% assign lineitems = customer_order.items | sort: 'created_date' %}they still render at random
![image](https://user-images.githubusercontent.com/7566324/35733816-7dc045ae-0827-11e8-855b-2606e9c40bd2.png)

**Comment by jarbi** [comment]
I don't know it matters but it is the "Order created"-notification i've modified so it's not really related to the storefront specifically.
I have overridden the ICustomerOrderBuilder.ToOrderModel(Domain.Cart.Model.LineItem lineItem) method to copy the cartlineitems created date to be able to sort them in the notification template.

My recommendation is that the platform should preserve the ordering of the cart lineitems during the conversion to the order by default.

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.6
