### ISSUE TITLE
The user should not have access to unrelated stores

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#67]
@vkrashenko commented on [Wed Feb 07 2018](https://github.com/VirtoCommerce/vc-platform/issues/1270)

### Steps to reproduce

1. Register in some store. For example in Electronics
2. Go to the platform and check that stores are NOT linked
3. Next go to the other store and try to login with your account from step 1.

Finally you will see next error, but successfully logged in,
![storeIssue.png](https://images.zenhubusercontent.com/595cebc061b4ca3b0a7348ac/43c0ed66-790e-460e-a859-3a896e7eaaa2)

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-storefront-core/releases/edit/v3.0.10
