### ISSUE TITLE
Limits anonymous access for CMS pages.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-storefront-core#70]
As a Content Manager, I want to limit access to anonymous access for CMS pages.

### want to block anonymous access to the page.
GIVEN Anonymous user
GIVEN CMS Page with Authorize = false. 
WHEN Open CMS Page
THEN Should be redirected to login
THEN After registration I should be redirected to CMS Page and be able to see content.

### Use authorize property to true/false 
Set to true if you want to block anonymous access to the page.
Set to false if you want to allow anonymous access to the page.
Default value is false

**Comment by OlegoO** [comment]
Example of authorize property
`````
---
layout: blog-layout
title: 'Demo'
permalink: blogs/news
authorize: true
---
`````

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-module-content/releases/tag/v2.13.9
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.10
