### ISSUE TITLE
User account should be locked out after X times of failed password attempts

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#77]
Version info: 
- Platform version: 2.13.21
- Storefront version: 3.0.10

### Expected behavior
User account should be locked out after X times of failed password attempts

### Actual behavior
User isn't locked out and/or not redirected to lockout page / do not receive any errors when trying to login again

**Comment by asvishnyakov** [comment]
@tatarincev How much more time we need to fix it? Requested by client project

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.1.0
