### ISSUE TITLE
Redirect anonymous user to the login page if a store has restricted access

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-storefront-core#78]
Anonimous user should be redirected to the login page if `workContext.CurrentStore.StoreState == StoreStatus.RestrictedAccess`.
When a user signs in, he should be redirected to the page that he requested initially.

Version info: 
- Storefront version: 3.0.10

**Comment by yecli** [comment]
Seems to be the same as #220.
