### ISSUE TITLE
Redirect user to his store after signing in to the wrong store

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-storefront-core#81]
We have multiple stores with the same domain name.
Each store has it's own customers.
Each customer can be registered only in one store.

Expected behavior:
When a customer signs in to the wrong store, we'd like to redirect him to the store where he was registered.

**Comment by tatarincev** [comment]
@artem-dudarev  has a solution for this task, before starting implementation need to ask him first.

**Comment by artem-dudarev** [comment]
We've implemented this behavior in our custom storefront, and since the generic storefront most likely doesn't need it, I'm closing the issue.
