### ISSUE TITLE
Add support of source maps for generated css from sass/scss

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#88]
@asvishnyakov commented on [Fri Sep 08 2017](https://github.com/VirtoCommerce/vc-storefront/issues/44)

Currently, storefront do not generate source maps for processed sass/scss files. To improve development process, add support of source maps. We need to upgrade libsassnet to latest version (LibSassProxy not needed in this case because of native x86/x64 switching). Also, libsass do not load & merge source maps if they already exist for processed sass/scss file. Fix it via https://github.com/Microsoft/sourcemap-toolkit

---

@asvishnyakov commented on [Fri Sep 08 2017](https://github.com/VirtoCommerce/vc-storefront/issues/44#issuecomment-327976634)

Research completed, implementation need additional time. On hold because of low priority

**Comment by tatarincev** [comment]
This issue has been closed because it has no longer relevant to the current operation nature of issues.
You may reopen this issue if it has been closed in error.
