### ISSUE TITLE
Add support of sass/scss importing

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-storefront-core#89]
@asvishnyakov commented on [Fri Sep 08 2017](https://github.com/VirtoCommerce/vc-storefront/issues/45)

Currently, if I try to import sass/scss in processed sass/scss, it fails:

> Line: @import "_bootstrap-variables.scss"; Compiler error: stdin:2: file to import not found or unreadable: _bootstrap-variables.scss Current dir:

Possible, we just need to include path of currently processed sass/scss to IncludePath(s) property of SassOptions passed to sass compiler. Need more research about it.

---

@OlegoO commented on [Wed Sep 13 2017](https://github.com/VirtoCommerce/vc-storefront/issues/45#issuecomment-329115171)

Need to update libsaas to latest version

**Comment by tatarincev** [comment]
This issue has been closed because it has no longer relevant to the current operation nature of issues.
You may reopen this issue if it has been closed in error.
